name: Reusable Workflow Demo

on:
  workflow_call:
    inputs:
      env_file:
        description: "Path to the environment file with variables"
        required: true
        type: string

jobs:
  set-env-vars:
    runs-on: ubuntu-latest
    steps:
      - name: Download the environment file
        uses: actions/download-artifact@v4
        with:
          name: ${{ inputs.env_file }}

      - name: List the files in the directory
        run: ls -l

      - name: Show tree structure
        run: tree -a

      - name: Show the content of the environment file
        run: cat .env

      - name: Load environment variables from .env file
        run: |
          # Read each line in the .env file and export it to GITHUB_ENV
          while IFS= read -r line; do
            echo "$line" >> $GITHUB_ENV
          done < .env

      - name: Use environment variables
        run: |
          echo "Environment Variable 1: $REACT_APP_API_URL"
          echo "Environment Variable 2: $REACT_APP_API_KEY"
          echo "REACT_PASS_THROUGH_GITHUB_ENV_ONE: $REACT_PASS_THROUGH_GITHUB_ENV_ONE"
          echo "REACT_PASS_THROUGH_GITHUB_ENV_TWO: $REACT_PASS_THROUGH_GITHUB_ENV_TWO"
